categories/urls.py
from django.urls import path

from categories.views import categories, category_detail

urlpatterns = [
    path("", categories, name="categories"),
    path("<int:category_id>/", category_detail, name="category_detail"),
]

criterionchallenge/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("categories/", include("categories.urls")),
    path("picks/", include("picks.urls")),
    path("user/", include("users.urls")),
]

home/urls.py
from django.urls import path

from home.views import home

urlpatterns = [
    path("", home, name="home"),
]

categories/models.py
import json

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from films.models import Film


class Category(models.Model):
    number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(52)], help_text="Enter a number between 1 and 52."
    )
    title = models.CharField(max_length=200)
    year = models.PositiveIntegerField(validators=[MinValueValidator(2020)])
    films = models.ManyToManyField(Film, related_name="categories", blank=True)
    custom_criteria = models.JSONField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "categories"
        unique_together = ("number", "year")
        ordering = ["number"]

    def __str__(self):
        return f"{self.number}: {self.title}"

    @property
    def num_films(self):
        return self.films.count()

    def clean(self):
        """Custom validation to enforce rules for films and custom_criteria."""

        if self.films.exists() and self.custom_criteria:
            raise ValidationError("Films and custom criteria cannot both be set at the same time.")

        if self.custom_criteria:
            try:
                json.dumps(self.custom_criteria)
                # TODO: validate custom_criteria against a schema with Cerberus
            except (TypeError, ValueError) as e:
                raise ValidationError(f"Invalid JSON in custom_criteria: {e}")

    def save(self, *args, **kwargs):
        """Override save to ensure the custom validation is called."""
        self.clean()
        super().save(*args, **kwargs)

categories/forms.py
import json

from django import forms
from django.db.models import Max

from categories.models import Category
from common.constants import CURRENT_YEAR


class PrettyJSONEncoder(json.JSONEncoder):
    def __init__(self, *args, indent, sort_keys, **kwargs):
        super().__init__(*args, indent=2, sort_keys=True, **kwargs)


class CustomJSONField(forms.JSONField):
    empty_values = [None, "", [], ()]


class CategoryForm(forms.ModelForm):
    custom_criteria = CustomJSONField(encoder=PrettyJSONEncoder)

    class Meta:
        model = Category
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.pk:
            self.fields["year"].initial = CURRENT_YEAR
            max_number = Category.objects.filter(year=CURRENT_YEAR).aggregate(Max("number"))["number__max"] or 0
            self.fields["number"].initial = max_number + 1

users/forms.py
from django import forms

from users.models import User, UserPreference


class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control"}),
        required=True,
        help_text='Having your date of birth is important because the pool of available films in some categories depends on your birth year. E.g. "Watch a film from the year you were born"',
    )

    class Meta:
        model = User
        fields = ["username", "date_of_birth"]
        widgets = {"username": forms.TextInput(attrs={"class": "form-control"})}
        help_texts = {"username": "Should match your Letterboxd username."}


class PickOrderCriteriaForm(forms.ModelForm):
    class Meta:
        model = UserPreference
        fields = ["pick_order_criteria"]
        widgets = {"pick_order_criteria": forms.HiddenInput()}


class SessionTimesForm(forms.ModelForm):
    class Meta:
        model = UserPreference
        fields = ["session_times"]
        widgets = {"session_times": forms.HiddenInput()}

categories/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, render
from django.utils.timezone import now

from categories.models import Category
from categories.utils import get_category_films, len_or_warning
from common.constants import CURRENT_YEAR
from films.models import FilmSession
from picks.models import Pick
from users.models import UserPreference, UserWatched, UserWatchlist


@login_required
def categories(request: HttpRequest):
    user = request.user
    user_watched_qs = UserWatched.objects.filter(user=user).values("films")
    user_watchlist_qs = UserWatchlist.objects.filter(user=user).values("films")
    category_list = []
    for category in Category.objects.filter(year=CURRENT_YEAR).order_by("number"):
        films = get_category_films(category, user)
        user_watched_films = films.filter(pk__in=user_watched_qs)
        user_watchlist_films = films.filter(pk__in=user_watchlist_qs)
        # user pick
        try:
            pick = Pick.objects.get(user=user, category=category)
            pick_film = pick.film
            is_locked = pick.locked
            is_watched = pick.film in user_watched_films
            is_watchlisted = pick.film in user_watchlist_films
            has_session = (
                FilmSession.objects.filter_by_datetime_preference(user)
                .filter(film=pick.film, datetime__gt=now())
                .exists()
            )
            pick = {
                "id": pick.pk,
                "film": str(pick_film),
                "locked": is_locked,
                "watched": is_watched,
                "watchlisted": is_watchlisted,
                "session": has_session,
            }
        except Pick.DoesNotExist:
            pick = None
        category_list.append(
            {
                "id": category.pk,
                "number": category.number,
                "title": category.title,
                "films_count": len_or_warning(films),
                "watched_count": len(user_watched_films),
                "watchlist_count": len(user_watchlist_films),
                "pick": pick,
            }
        )
    # Sorting logic
    sort_param = request.GET.get("sort", "number")
    reverse = sort_param.startswith("-")
    sort_key = sort_param.lstrip("-")
    valid_sort_keys = {"number", "films_count", "watched_count", "watchlist_count"}
    if sort_key in valid_sort_keys:
        category_list.sort(key=lambda x: x[sort_key], reverse=reverse)
    return render(request, "categories.html", {"categories": category_list})


@login_required
def category_detail(request: HttpRequest, category_id: int):
    user = request.user
    category = get_object_or_404(Category, id=category_id)
    preferences, _ = UserPreference.objects.get_or_create(user=user)
    # Fetch films
    films = get_category_films(category, user)
    # Apply filters
    if preferences.filter_not_watched:
        films = [film for film in films if not UserWatched.objects.filter(user=user, films=film).exists()]
    if preferences.filter_watchlisted:
        films = [film for film in films if UserWatchlist.objects.filter(user=user, films=film).exists()]
    if preferences.filter_with_sessions:
        films = [film for film in films if FilmSession.objects.filter(film=film, datetime__gt=now()).exists()]
    # Prepare response
    film_objects = [
        {
            "id": film.pk,
            "title": film.title,
            "year": film.year,
            "runtime": film.runtime,
            "directors": ", ".join(map(str, film.directors.all())),
            "url": film.letterboxd_url,
            "watched": UserWatched.objects.filter(user=user, films=film).exists(),
            "watchlisted": UserWatchlist.objects.filter(user=user, films=film).exists(),
            "is_pick": Pick.objects.filter(user=user, category=category, film=film).exists(),
            "picked": Pick.objects.filter(user=user, year=CURRENT_YEAR, film=film).exists(),
            "sessions": [
                {"venue": s.venue, "date": s.datetime}
                for s in FilmSession.objects.filter(film=film, datetime__gt=now())
            ],
        }
        for film in films
    ]
    pick = Pick.objects.filter(user=user, category=category).first()
    response = {
        "category": {
            "id": category.pk,
            "number": category.number,
            "title": category.title,
            "films": film_objects,
            "locked": pick.locked if pick else False,
        },
        "filters": {
            "filter_not_watched": preferences.filter_not_watched,
            "filter_watchlisted": preferences.filter_watchlisted,
            "filter_with_sessions": preferences.filter_with_sessions,
        },
    }
    return render(request, "category.html", response)

home/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.shortcuts import redirect, render

from common.templatetags.common_extras import more_than_a_month_ago
from users.models import User, UserWatched, UserWatchlist


@login_required
def home(request: HttpRequest):
    user = User.objects.get(pk=request.user.pk)
    if not user.date_of_birth:
        messages.warning(request, "You need to set your birth date. Go to Profile.")
    try:
        watched = UserWatched.objects.get(user=user)
        watchlist = UserWatchlist.objects.get(user=user)
        if not watched or not watchlist:
            messages.warning(request, "You need to refresh your film stats. Go to Profile > Stats.")
        if more_than_a_month_ago(watched.updated_at) or more_than_a_month_ago(watchlist.updated_at):
            messages.warning(request, "You haven't updated your film stats in a while...")
    except (UserWatched.DoesNotExist, UserWatchlist.DoesNotExist):
        messages.warning(request, "You need to refresh your film stats. Go to Profile > Stats.")
    if not messages.get_messages(request):
        return redirect("categories")
    return render(request, "home.html")

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Build your Criterion Challenge">
    <meta name="keywords"
          content="Criterion Collection, Criterion Challenge, Letterboxd">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Criterion Challenge
      {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
      <div class="container container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Criterion Challenge</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Left-aligned links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
          </ul>
          <!-- Right-aligned logout button -->
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}" class="d-flex">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-primary">Logout</button>
            </form>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
    <footer class="mt-auto bg-light py-3 text-center">
      <small class="container">
        <span class="mb-0">Criterion Challenge 2025. No rights reserved at all.</span>
      </small>
    </footer>
    <script src="https://kit.fontawesome.com/55b6a23ffe.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
  </body>
</html>

templates/categories.html
{% extends "base.html" %}
{% block content %}
  <h1>Categories</h1>
  <!-- Sorting Dropdown -->
  <form method="get" class="mb-3">
    <label for="sort" class="form-label">Sort by:</label>
    <select name="sort"
            id="sort"
            class="form-select"
            onchange="this.form.submit()">
      <option value="number"
              {% if request.GET.sort == "number" %}selected{% endif %}>Category ↓</option>
      <option value="-number"
              {% if request.GET.sort == "-number" %}selected{% endif %}>Category ↑</option>
      <option value="films_count"
              {% if request.GET.sort == "films_count" %}selected{% endif %}>Films ↓</option>
      <option value="-films_count"
              {% if request.GET.sort == "-films_count" %}selected{% endif %}>Films ↑</option>
      <option value="watchlist_count"
              {% if request.GET.sort == "watchlist_count" %}selected{% endif %}>Watchlist ↓</option>
      <option value="-watchlist_count"
              {% if request.GET.sort == "-watchlist_count" %}selected{% endif %}>Watchlist ↑</option>
    </select>
  </form>
  <div class="row row-cols-1 row-cols-md-4 g-2 mb-4">
    {% for category in categories %}
      <div class="col">
        <div class="card h-100 text-white border-2 {% if category.pick.watched %}bg-dark opacity-25 hover-opacity-75{% elif category.pick.locked %}border-secondary{% endif %}">
          <h4 class="card-header">
            <small>{{ category.number }}.</small> {{ category.title }}
            {% if category.pick.locked %}
              <span title="locked"><i class="fa-solid fa-lock" style="color: #B58900" title="locked"></i></span>
            {% endif %}
          </h4>
          <ul class="card-body p-0 list-group list-group-flush">
            <li class="list-group-item">
              <div class="d-flex justify-content-around">
                <div class="center" title="films">
                  <i class="fa-solid fa-film" style="color: #FF8001"></i> {{ category.films_count }}
                </div>
                <div class="center" title="watched">
                  <i class="fa-solid fa-eye" style="color: #01E053;"></i> {{ category.watched_count|default:0 }}
                </div>
                <div class="center" title="watchlisted">
                  <i class="fa-solid fa-clock" style="color: #40BCF4;"></i>  {{ category.watchlist_count|default:0 }}
                </div>
              </div>
            </li>
            {% if category.pick %}
              <li class=" list-group-item">
                <strong class="fs-4">{{ category.pick.film }}</strong>
                {% if category.pick.watched %}
                  <i class="fa-solid fa-eye" style="color: #01E053;" title="watched"></i>
                {% elif category.pick.watchlisted %}
                  <i class="fa-solid fa-clock" style="color: #40BCF4;" title="watchlisted"></i>
                {% endif %}
                {% if category.pick.session %}
                  <i class="fa-solid fa-ticket"
                     style="color: #FF8001"
                     title="with session soon"></i>
                {% endif %}
              </li>
            {% endif %}
          </ul>
          <div class="card-footer text-end">
            {% if category.pick %}
              <input type="checkbox"
                     class="btn-check"
                     id="btncheck{{ category.pick.id }}"
                     {% if category.pick.locked %}checked{% endif %}
                     autocomplete="off"
                     onchange="toggleLock({{ category.pick.id }})">
              <label class="btn btn-secondary" for="btncheck{{ category.pick.id }}">
                {% if category.pick.locked %}
                  Unlock
                {% else %}
                  Lock
                {% endif %}
              </label>
            {% endif %}
            <a href="{% url 'category_detail' category.id %}"
               class="btn {% if category.pick.watched %}btn-dark{% else %}btn-primary{% endif %}">Films</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <a href="{% url 'complete_picks' %}" class="btn btn-primary mb-3">Randomize Picks</a>
  <script>
    function toggleLock(pickId) {
      console.log("pickId", pickId)
      fetch(`/picks/toggle-lock/`, {
      method: "PATCH",
      headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": "{{ csrf_token }}",
      },
      body: JSON.stringify({ pick_id: pickId }),
      })
      .then((response) => {
          if (response.ok) {
              return response.json();
          }
          throw new Error("Failed to update lock status");
      })
      .then((data) => {
        window.location.reload();
      })
      .catch((error) => {
          console.error(error);
          alert("Failed to update lock status.");
      });
    }
  </script>
  <style>
    .hover-opacity-75 {
      transition: opacity 0.2s ease, border 0.2s ease;
    }
    .hover-opacity-75:hover {
      opacity: 0.75 !important;
      border: 2px solid var(--bs-primary) !important;
    }
  </style>
{% endblock content %}

templates/category.html
{% extends "base.html" %}
{% block content %}
  <h5>Category {{ category.number }}</h5>
  <h1>
    {{ category.title }}
    {% if category.locked %}<i class="fa-solid fa-lock" title="locked"></i>{% endif %}
  </h1>
  <!-- Filters -->
  <div class="btn-group mb-3" role="group" aria-label="Film filters">
    <input type="checkbox"
           class="btn-check"
           id="filter-not-watched"
           autocomplete="off"
           {% if filters.filter_not_watched %}checked{% endif %}
           onchange="toggleFilters({'filter_not_watched': {{ filters.filter_not_watched|yesno:"false,true" }} })">
    <label class="btn btn-primary" for="filter-not-watched">Not Watched</label>
    <input type="checkbox"
           class="btn-check"
           id="filter-watchlisted"
           autocomplete="off"
           {% if filters.filter_watchlisted %}checked{% endif %}
           onchange="toggleFilters({'filter_watchlisted': {{ filters.filter_watchlisted|yesno:"false,true" }} })">
    <label class="btn btn-primary" for="filter-watchlisted">Watchlisted</label>
    <input type="checkbox"
           class="btn-check"
           id="filter-with-sessions"
           autocomplete="off"
           {% if filters.filter_with_sessions %}checked{% endif %}
           onchange="toggleFilters({'filter_with_sessions': {{ filters.filter_with_sessions|yesno:"false,true" }} })">
    <label class="btn btn-primary" for="filter-with-sessions">With Sessions</label>
  </div>
  <section class="row row-cols-1 row-cols-md-4 g-2 mb-4">
    {% for film in category.films %}
      <div class="col">
        <div class="card h-100  border-2 {% if film.is_pick %}bg-primary text-white{% elif film.watched %}opacity-25 hover-opacity-75{% endif %}">
          <div class="card-header text-white ">
            <h4>
              {{ film.title }} <small><small class="fw-lighter">({{ film.year }})</small></small>
            </h4>
            <div>{{ film.directors }}</div>
          </div>
          <div class="card-body">
            <small>{{ film.runtime }} mins</small>
          </div>
          {% if film.sessions %}
            <ul class="list-group list-group-flush">
              {% for session in film.sessions %}<li class="list-group-item">{{ session.date }}, {{ session.venue }}</li>{% endfor %}
            </ul>
          {% endif %}
          <div class="card-footer">
            <a href="{{ film.url }}"
               class="btn btn-dark"
               target="_blank"
               rel="noopener noreferrer">Letterboxd</a>
            <button class="btn btn-danger"
                    {% if film.picked or category.locked %}disabled{% endif %}
                    {% if category.locked %}title="Category locked"{% endif %}
                    {% if film.watched %}title="Already watched"{% endif %}
                    onclick="setPick({{ category.id }}, {{ film.id }})">Pick</button>
          </div>
        </div>
      </div>
    {% empty %}
      <p>No films in this category.</p>
    {% endfor %}
  </section>
  <script>
    function setPick(categoryId, filmId) {
        fetch(`/picks/set-category-pick/`, {
        method: "PATCH",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}",
        },
        body: JSON.stringify({ category_id: categoryId, film_id: filmId }),
        })
        .then((response) => {
            if (response.ok) {
                return response.json();
            }
            throw new Error("Failed to update pick");
        })
        .then((data) => {
          window.location.reload();
        })
        .catch((error) => {
            console.error(error);
            alert("Failed to update pick.");
        });
    }

    function toggleFilters(filters) {
      fetch(`/user/preferences/filters/update/`, {
      method: "PATCH",
      headers: {
          "Content-Type": "application/json",
          "X-CSRFToken": "{{ csrf_token }}",
      },
      body: JSON.stringify(filters),
      })
      .then((response) => {
          if (response.ok) {
              return response.json();
          }
          throw new Error("Failed to update lock status");
      })
      .then((data) => {
        window.location.reload();
      })
      .catch((error) => {
          console.error(error);
          alert("Failed to update lock status.");
      });
    }
  </script>
  <style>
    .hover-opacity-75 {
      transition: opacity 0.2s ease;
    }
    .hover-opacity-75:hover {
      opacity: 0.75 !important;
    }
  </style>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block content %}
  {% if user.is_authenticated %}
    <h2>Hello, {{ user.get_full_name|default:user.username }}!</h2>
    {% load common_extras %}
    {% if messages %}
      <div class="messages">
        {% for message in messages %}<div class="alert alert-{{ message.tags }}">{{ message|safe }}</div>{% endfor %}
      </div>
    {% endif %}
  {% endif %}
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
  <h1>Profile</h1>
  {% if error %}<div class="alert alert-danger">{{ error }}</div>{% endif %}
  {% if success %}<div class="alert alert-success">{{ success }}</div>{% endif %}
  <form method="post" class="mt-4">
    {% csrf_token %}
    <div class="row mb-3">
      <div class="col">
        <label for="id_first_name" class="col-sm-3 col-form-label">First Name</label>
        <div class="col-sm-12">{{ form.first_name }}</div>
      </div>
      <div class="col">
        <label for="id_last_name" class="col-sm-3 col-form-label">Last Name</label>
        <div class="col-sm-12">{{ form.last_name }}</div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="id_date_of_birth" class="col-sm-3 col-form-label">Date of Birth</label>
      <div class="col-sm-9">
        {{ form.date_of_birth }}<small id="dateHelp" class="form-text text-muted">{{ form.date_of_birth.help_text }}</small>
      </div>
    </div>
    <div class="mt-4">
      <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
      <button type="submit" class="btn btn-primary">Save Changes</button>
    </div>
  </form>
  <hr class="mt-5" />
  {% include "profile/stats.html" %}
  {% include "profile/csv_upload.html" %}
  <hr class="mt-5" />
  {% include "profile/pick_preferences.html" %}
{% endblock content %}